name: Reusable Workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        default: World
        required: true
    outputs:
      current-time:
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ inputs.who-to-greet }}"
      - id: time
        run: |
          echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.time.outputs.time }}
